name: assignment-test
on: [push]
jobs:
    full-test:
        container: cuaesd/aesd-autotest:assignment7-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Run full test

